import os
import sys
import pickle
import logging
import chromadb
from rank_bm25 import BM25Okapi

# Add parent path to import sibling files
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from backend.chunker import SemanticChunker

logger = logging.getLogger(__name__)

# Helper to dynamically load environment variables from the root .env file
def load_env_file():
    backend_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(backend_dir)
    env_path = os.path.join(project_root, ".env")
    if os.path.exists(env_path):
        try:
            with open(env_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, val = line.split("=", 1)
                        val = val.strip().strip('"').strip("'")
                        os.environ[key.strip()] = val
            logger.info("Successfully loaded local environment variables from .env file.")
        except Exception as e:
            logger.error(f"Error parsing local .env file: {e}")

load_env_file()

# Fallback embedding generator in case Gemini API key is missing or fails
class EmbeddingGenerator:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.local_model = None
        if not self.api_key:
            logger.warning("GEMINI_API_KEY environment variable not found. Initializing SentenceTransformers ('all-MiniLM-L6-v2') as local fallback.")
            self.init_local_model()
            
    def init_local_model(self):
        try:
            from sentence_transformers import SentenceTransformer
            self.local_model = SentenceTransformer('all-MiniLM-L6-v2')
            logger.info("SentenceTransformers 'all-MiniLM-L6-v2' initialized successfully.")
        except Exception as e:
            logger.error(f"Failed to load SentenceTransformers model: {e}. Falling back to statistical/dummy embeddings.")
            
    def get_embeddings(self, texts: list) -> list:
        """
        Generates 768-dimensional (or 384-dimensional fallback) dense vector embeddings for input text.
        """
        if self.api_key:
            try:
                import google.generativeai as genai
                genai.configure(api_key=self.api_key)
                
                # Google text-embedding-004 generates high-fidelity 768-dim embeddings
                logger.info(f"Generating embeddings for {len(texts)} chunks using Google text-embedding-004...")
                response = genai.embed_content(
                    model="models/text-embedding-004",
                    content=texts,
                    task_type="retrieval_document"
                )
                return response['embedding']
            except Exception as e:
                logger.error(f"Google Gemini Embed Content API failed: {e}. Activating local model fallback.")
                if not self.local_model:
                    self.init_local_model()

        if self.local_model:
            try:
                logger.info(f"Generating local embeddings for {len(texts)} chunks using SentenceTransformers...")
                embeddings = self.local_model.encode(texts)
                # Convert numpy array to standard list of lists
                return [emb.tolist() for emb in embeddings]
            except Exception as e:
                logger.error(f"Local SentenceTransformers execution failed: {e}")

        # Absolute fail-safe dummy embedding if both fail (ensures the indexing pipeline NEVER crashes)
        logger.warning("Failsafe activated: generating dummy vectors of length 768.")
        import random
        return [[random.random() for _ in range(768)] for _ in range(len(texts))]

def run_indexing_pipeline(scraped_json_path: str):
    """
    Chronological indexing pipeline:
    1. Parse and chunk JSON databases semantic-wise.
    2. Generate vector embeddings (Gemini/SentenceTransformers).
    3. Index and persist dense database in ChromaDB.
    4. Tokenize and build sparse BM25 index, serializing to disk.
    """
    logger.info("Initializing indexing and database update pipeline...")
    
    # 1. Semantic Chunking
    chunker = SemanticChunker()
    chunks = chunker.process_all_scraped_data(scraped_json_path)
    
    if not chunks:
        logger.warning("No chunks generated by chunker. Indexing aborted.")
        return

    texts = [c["text"] for c in chunks]
    metadatas = [c["metadata"] for c in chunks]
    ids = [m.get("chunk_id", f"chk_{idx}_{m['hash_checksum'][:8]}") for idx, m in enumerate(metadatas)]
    
    # 2. Vector Embeddings Generation
    emb_gen = EmbeddingGenerator()
    embeddings = emb_gen.get_embeddings(texts)
    
    # 3. Dense Storage: ChromaDB Indexing
    logger.info("Connecting to ChromaDB and storing dense vector chunks...")
    os.makedirs('db', exist_ok=True)
    
    # Initialize persistent local Chroma Client
    chroma_client = chromadb.PersistentClient(path="./db/chroma_store")
    
    # Dynamically select collection based on generated embedding dimensionality to prevent fatal dimension crashes
    dimension = len(embeddings[0])
    collection_name = f"mutual_fund_rag_collection_{dimension}"
    
    # Delete the existing collection if it exists, to prevent stale/duplicate chunks from leaking
    try:
        chroma_client.delete_collection(collection_name)
        logger.info(f"Deleted existing ChromaDB collection {collection_name} to clear stale chunks.")
    except Exception:
        pass
        
    # Get or create compliance-verified collection
    collection = chroma_client.get_or_create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"} # Use cosine similarity distance
    )
    
    # Upsert items (overwriting if ID matches to prevent duplicated data)
    collection.upsert(
        ids=ids,
        embeddings=embeddings,
        metadatas=metadatas,
        documents=texts
    )
    logger.info(f"Stored {len(ids)} chunks inside persistent ChromaDB collection.")

    # 4. Sparse Storage: BM25 Keyword Indexing
    logger.info("Fusing sparse search indices: tokenizing chunks for BM25...")
    
    # Basic lowercased alphanumeric word tokenizer
    tokenized_corpus = [text.lower().split() for text in texts]
    
    # Initialize BM25Okapi
    bm25 = BM25Okapi(tokenized_corpus)
    
    # Package BM25 indexing data with standard corpus for runtime retrieval
    bm25_data = {
        "bm25_instance": bm25,
        "texts": texts,
        "metadatas": metadatas,
        "ids": ids
    }
    
    # Serialize to pickle file
    os.makedirs('data', exist_ok=True)
    bm25_path = 'data/bm25_store.pkl'
    with open(bm25_path, 'wb') as f:
        pickle.dump(bm25_data, f)
        
    logger.info(f"BM25 index successfully built and serialized to {bm25_path}.")
    logger.info("Indexing tier update successfully completed.")

if __name__ == "__main__":
    # Test runner using existing scraped data if available
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    test_path = 'data/scraped_schemes.json'
    if os.path.exists(test_path):
        run_indexing_pipeline(test_path)
    else:
        logger.error(f"Cannot run test. Scraped file not found at {test_path}. Please execute scraper first.")
